DPO:
  - loss_type
DPO_NOISE:
  - reward_model
  - noise_type
  - noise_level
  - loss_type
DDP:
  - r
  - rho
  - loss_type
DPP:
  - p
  - pi
  - loss_type
DPR:
  - g
  - gamma
  - loss_type
DRO_DPR:
  - dro
  - omega
  - loss_type
DR_DPO:
  - beta_prime
  - loss_type
MIX:
  - r
  - rho
  - p
  - pi
  - g
  - gamma
  - loss_type
