DPO:
  - beta
  - loss_type
DDP:
  - beta
  - r
  - rho
  - loss_type
DPP:
  - beta
  - p
  - pi
  - loss_type
DPR:
  - beta
  - g
  - gamma
  - loss_type
DRO_DPR:
  - beta
  - dro
  - omega
  - loss_type
MIX:
  - beta
  - r
  - rho
  - p
  - pi
  - g
  - gamma
  - loss_type
