Q0.5B: Qwen/Qwen1.5-0.5B
Q1.8B: Qwen/Qwen1.5-1.8B
Q4B: Qwen/Qwen1.5-4B
Q7B: Qwen/Qwen1.5-7B
Qc0.5B: Qwen/Qwen1.5-0.5B-Chat
Qc1.8B: Qwen/Qwen1.5-1.8B-Chat
Qc4B: Qwen/Qwen1.5-4B-Chat
Qc7B: Qwen/Qwen1.5-7B-Chat
Py70M: EleutherAI/pythia-70m-deduped
Py160M: EleutherAI/pythia-160m-deduped
Py410M: EleutherAI/pythia-410m-deduped
Py1B: EleutherAI/pythia-1b-deduped
Py1.4B: EleutherAI/pythia-1.4b-deduped
Py2.8B: EleutherAI/pythia-2.8b-deduped
Py6.9B: EleutherAI/pythia-6.9b-deduped
Ph1.5B: microsoft/phi-1_5
Ph2B: microsoft/phi-2
Pm3B: microsoft/Phi-3-mini-4k-instruct
G2B: google/gemma-2b
G7B: google/gemma-7b
M7B: mistralai/Mistral-7B-v0.1
L8B: meta-llama/Meta-Llama-3-8B-Instruct