PP:
  id: PKU-Alignment/beaver-7b-v1.0-reward
  reverse: false

PH:
  id: PKU-Alignment/beaver-7b-v1.0-cost
  reverse: true
# U:
#   id: PKU-Alignment/beaver-7b-v1.0-reward
#   reverse: false
U:
  id: openbmb/Eurus-RM-7b
  reverse: false
# U:
#   id: OpenAssistant/reward-model-deberta-v3-base
#   reverse: false

RMAB_PG:
  id: openbmb/Eurus-RM-7b
  reverse: false

RMAB_TG:
  id: openbmb/Eurus-RM-7b
  reverse: false
