compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
machine_rank: 0
main_training_function: generate_responses
num_machines: 1
num_processes: 4
same_network: true
main_process_port: 63851